### ISSUE TITLE
Cannot start application

### ISSUE THREAD

**Issue by yeager-j** [feathers-plus/cli#21]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

### Expected behavior

App compiles and runs successfully.

### Actual behavior

Immediately after generating the options and the app, I run `npm start` and am greeted with this error:

```
> ts-node --files src/


/Users/jackson/WebstormProjects/auth0/auth0-demo-server/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/channels.ts(4,18): error TS2339: Property 'channel' does not exist on type 'Application<{}>'.
src/channels.ts(11,9): error TS2339: Property 'channel' does not exist on type 'Application<{}>'.
src/channels.ts(22,11): error TS2339: Property 'channel' does not exist on type 'Application<{}>'.
src/channels.ts(25,11): error TS2339: Property 'channel' does not exist on type 'Application<{}>'.
src/channels.ts(42,7): error TS2339: Property 'publish' does not exist on type 'Application<{}>'.
src/channels.ts(42,16): error TS7006: Parameter 'data' implicitly has an 'any' type.
src/channels.ts(42,22): error TS7006: Parameter 'hook' implicitly has an 'any' type.
src/channels.ts(50,16): error TS2339: Property 'channel' does not exist on type 'Application<{}>'.

    at createTSError (/Users/jackson/WebstormProjects/auth0/auth0-demo-server/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/Users/jackson/WebstormProjects/auth0/auth0-demo-server/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/Users/jackson/WebstormProjects/auth0/auth0-demo-server/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/Users/jackson/WebstormProjects/auth0/auth0-demo-server/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/jackson/WebstormProjects/auth0/auth0-demo-server/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
```

### System configuration

Node v10.4.0
Feathers-Plus v0.7.64
TypeScript v2.7.2

Running on Mac OS Mojave v10.14

**Comment by eddyystop** [comment]
Please post generator issues in feathers-plus/generator-feathers-plus.
